name: Build eco.pgn

on:
  workflow_dispatch: {}          # run by button
  schedule:
    - cron: "0 3 * * 1"          # optional: weekly update (Mon 03:00 UTC)

permissions:
  contents: write                # allow pushes from GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Checkout lichess chess-openings
        uses: actions/checkout@v4
        with:
          repository: lichess-org/chess-openings
          path: chess-openings

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install chess

      - name: Build dist (eco.pgn, etc.)
        working-directory: chess-openings
        run: make

      - name: Copy eco.pgn into this repo
        run: |
          mkdir -p data
          cp chess-openings/dist/eco.pgn data/eco.pgn

      - name: Commit to branch and open PR
        run: |
          BRANCH=update-eco-$(date +%Y%m%d)
          git checkout -b "$BRANCH"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/eco.pgn
          git commit -m "Update eco.pgn"
          git push -u origin "$BRANCH"

      - name: Upload eco.pgn as a workflow artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: eco.pgn
          path: data/eco.pgn
